In [1]:
import numpy as np
np.__version__

'1.18.1'

In [4]:
np.array([1,2,"1"])

array(['1', '2', '1'], dtype='<U21')

In [5]:
classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)

list

In [6]:
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [7]:
numpy_array.shape

(6,)

In [8]:
np.array([2,4]).mean()

3.0

In [9]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [10]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])

In [11]:
matrix1[0, :]

array([1, 2, 3])

In [12]:
matrix1[:, -1]

array([3, 6, 9])

In [13]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])

In [14]:
matrix2.sum()

47

In [15]:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [16]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [17]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [18]:
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])

array([[ 9, 11],
       [13, 15]])